# Generated by Django 3.2.5 on 2021-07-08 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='descripcionropa',
            old_name='genero',
            new_name='grupoRopa',
        ),
    ]
