# Generated by Django 3.2.5 on 2021-07-08 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_genero_descripcionropa_gruporopa'),
    ]

    operations = [
        migrations.AddField(
            model_name='descripcionropa',
            name='stock',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='descripcionropa',
            name='talla',
            field=models.CharField(max_length=50),
        ),
    ]
