# Generated by Django 3.2.5 on 2021-07-08 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210708_0854'),
    ]

    operations = [
        migrations.AddField(
            model_name='descripcionropa',
            name='color',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
